# Generated by Django 4.2.24 on 2025-09-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_sick', models.CharField(max_length=100)),
                ('a_time', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_loc', models.CharField(max_length=100)),
            ],
        ),
    ]
